version: '3.8'

services:

    db:
        image: postgres:14.4-alpine
        restart: always
        environment:
            POSTGRES_PASSWORD: postgres
            POSTGRES_DB: manga-view
        ports:
            - "5432:5432"